version: 2.1

parameters:
  create_review_app:
    type: boolean
    default: false
  test_string:
    type: string
    default: "nonono"

executors:

  default:
    working_directory: ~/workspace
    docker:
      - image: circleci/node:10.18.0
    environment:
      NPM_CONFIG_LOGLEVEL: warn
      TERM: xterm-color
      TZ: /usr/share/zoneinfo/Asia/Tokyo

commands:

jobs:

  terraform_plan:
    executor: default
    steps:
      - checkout
      - run:
          name: Test
          command: echo test

  create_review_app:
    executor: default
    steps:
      - checkout
      - run:
          name: Test from pipeline
          command: echo << pipeline.parameters.test_string >>

workflows:

  build:
    unless: << pipeline.parameters.create_review_app >>
    jobs:
      - terraform_plan

  create_review_app_flow:
    when: << pipeline.parameters.create_review_app >>
    jobs:
      - create_review_app
