version: 2.1

parameters:

executors:

  node:
    working_directory: ~/workspace
    docker:
      - image: circleci/node:10.18.0

commands:

jobs:

  test:
    executor: node
    steps:
      - checkout
      - run:
          name: Test
          command: npx jest --config {}

workflows:

  build:
    jobs:
      - test
