version: 2.1

parameters:

  create_review_app:
    type: boolean
    default: false
  test_string:
    type: string
    default: "nonono"

executors:

  python:
    working_directory: ~/workspace
    docker:
      - image: circleci/python:stretch

  terraform:
    docker:
      - image: hashicorp/terraform:0.12.18

commands:

  install_awscli:
    steps:
      - run:
          name: Install awscli
          command: |
            sudo sh -c 'curl https://bootstrap.pypa.io/get-pip.py | python'
            sudo pip install awscli

jobs:

  terraform_plan:
    executor: terraform
    steps:
      - checkout
      - run:
          name: Terraform init
          command: terraform init
      - run:
          name: Terraform plan
          command: terraform plan

  create_review_app:
    executor: python
    steps:
      - checkout
      - install_awscli
      - run:
          name: Test from pipeline
          command: echo << pipeline.parameters.test_string >>

workflows:

  build:
    unless: << pipeline.parameters.create_review_app >>
    jobs:
      - terraform_plan

  create_review_app_flow:
    when: << pipeline.parameters.create_review_app >>
    jobs:
      - create_review_app
