version: 2.1

parameters:

executors:

  python:
    working_directory: ~/workspace
    docker:
      - image: circleci/python:stretch

  terraform:
    docker:
      - image: hashicorp/terraform:0.12.18

commands:

  install_awscli:
    steps:
      - run:
          name: Install awscli
          command: sudo pip install awscli

jobs:

  terraform_plan:
    executor: terraform
    steps:
      - checkout
      - run:
          name: Terraform init
          command: terraform init
      - run:
          name: Terraform plan
          command: terraform plan

workflows:

  build:
    jobs:
      - terraform_plan
